apiVersion: v1
data:
  default.conf: "server {\n  listen 80;\n  server_name _;\n\n  location = /public\
    \ {\n    default_type text/plain;\n    return 200 \"public endpoint\\n\";\n  }\n\
    \n  location = /admin {\n    default_type text/plain;\n    return 200 \"admin\
    \ endpoint\\n\";\n  }\n\n  location / {\n    default_type text/plain;\n    return\
    \ 404 \"not found\\n\";\n  }\n}\n"
kind: ConfigMap
metadata:
  name: l7-nginx-config
  namespace: l7-demo
