apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 10.10.10.200
  labels:
    lb-ipam: lan
  name: web
  namespace: lb-ipam-demo
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31116
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lb-ipam-web
  sessionAffinity: None
  type: LoadBalancer
