apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.1.89
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: k8s-worker1
    targetRef:
      kind: Pod
      name: web-84df6fdf59-sbdkh
      namespace: lb-ipam-demo
      uid: bc57841b-3a26-47c9-9b89-899abcd70903
  - addresses:
    - 10.244.1.222
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: k8s-worker1
    targetRef:
      kind: Pod
      name: web-84df6fdf59-lchxr
      namespace: lb-ipam-demo
      uid: d422bae5-df4e-4eba-b7f5-9205eecba43d
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-29T21:02:58Z"
    creationTimestamp: "2026-07-28T23:03:19Z"
    generateName: web-bgp-
    generation: 8
    labels:
      bgp-advertise: "true"
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: web-bgp
      lb-ipam: bgp
    name: web-bgp-gm95m
    namespace: lb-ipam-demo
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: web-bgp
      uid: 0766d664-4f13-4693-ba4f-3292b60c9444
    resourceVersion: "194796"
    uid: 5d1cdc1f-87eb-4d78-9b2c-641d009d70a5
  ports:
  - name: http
    port: 80
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
